name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        rustup override set nightly 
        cargo build --verbose
    - name: Run tests
      run: |
        rustup override set nightly 
        cargo test --workspace bth--verbose
